### ISSUE TITLE
Slide 6 - Removing Integration Management (Integration Records)

### ISSUE THREAD

**Issue by fvet** [microsoft/BCUpgrade#1]
> We will support the integration records for one year. We have added an unique identifier $systemID to every table and **will add ModifiedOn date in following releases** and refactor CRM integration and APIs to fully use the new system

Should we expect **each** standard / extension table to receive a new (system) field 'ModifiedOn Date'? Next to the Date, would it make sense storing the **ModifiedTime** and **ModifiedUser** as well?

**Comment by nikolakukrika** [comment]
Great question - in order to fully deprecate the Integration Record, we need the "audit feature". Each record will track the ModifiedTime and ModifiedBy fields. I have added it to the slide. 

We are planning to release the "Audit feature" with 16 (2020 spring), I will post if the plans change.

**Comment by nikolakukrika** [comment]
Updated the powerpoint, please close the issue if you are satisfied with the answer.
