### ISSUE TITLE
Slide 21 (Buffer table example): what is an upgrade range?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#12]
Slide 21 (Buffer table example) mentions:

> ID must be in upgrade range, name needs to be different we recommend prefixing with UPG – 

Sounds like there exist a specif upgrade ID range, but I recon this a range I as developing company owns? In other words make it a bit more specific what an upgrade range is.

**Comment by nikolakukrika** [comment]
Partners should know this. Upgrade range is 104000. I have added range within license, this will work as well.

**Comment by lvanvugt** [comment]
Never heard of this range. Been around some time already (though not at a partner anymore)

**Comment by nikolakukrika** [comment]
Well, all of the Microsoft upgrade objects are in this range. They are in the license as far as I know, so I recommend using these.

Any object range that is in the license will work for buffer tables, there is no special requirements.

**Comment by lvanvugt** [comment]
OK, I know it as the MS range. Hadn't looked at it this way.
