### ISSUE TITLE
Slide 23 (Example of upgrade code): extend the example code

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#13]
Extend the example code with what is recommended:

> ... to cleanup the buffer table after done with upgrade, delete the object and force sync the SQL

Will be very helpful to many

**Comment by nikolakukrika** [comment]
Won't fix on this one :) . It should be known and documented.

**Comment by lvanvugt** [comment]
If it's documented please share a link. At least I am not aware of any documentation on this. I guess al lot more are.

**Comment by nikolakukrika** [comment]
Well how do you cleanup the table in the running system in C/AL?
Delete and Sync-NavTenant with force. Do we really need to document this?
This was done for every upgrade from before 14.x

**Comment by lvanvugt** [comment]
Makes more sense now. It looked like it should be added to the AL code, but that's now apparently not what was meant. Nevertheless, the fact that I am asking will probably get others asking too, so do you want to prevent that or not.
A simple as addition could be: Delete-NAVApplicationObject and Sync-NavTenant with force.
