### ISSUE TITLE
Slide 24 (Recommendations on how to resolve changing the key): Shadow Table pattern

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#15]
Please explain (or give reference to) what a Shadow Table pattern is.

**Comment by nikolakukrika** [comment]
We don't have it documented. Is it enough to reference a codeunit as I did?

**Comment by lvanvugt** [comment]
Cannot reopen an issue.

If the reference seemed enough to me I would not have reported this. It's the first I hear of it and would like to get some more info. I recon more people using the slide deck will.

**Comment by nikolakukrika** [comment]
Interesting, I assumed it is possible to reopen. Please look at the codeunit 5477 implementation, I don't have time to write patterns right now, nor we have a place to publish them.

**Comment by lvanvugt** [comment]
Will have a look.
