### ISSUE TITLE
Slide 28 (Renaming fields or tables): wrong SetTableSyncSetup parameter

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#16]
On slide 28 (Renaming fields or tables) the text mentions _Force_:

> For added objects (table/fields) you can simply rename and set **Force** for Table Sync Setup (if needed)

The code example however "says" _Copy_:

`DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Report Layout Selection",DATABASE::"UPG Report Layout Selection", TableSynchSetup.Mode::Copy);`

I guess the code should be:

`DataUpgradeMgt.SetTableSyncSetup(DATABASE::"Report Layout Selection", 0, TableSynchSetup.Mode::Force);`

**Comment by nikolakukrika** [comment]
Correct. Thanks :)
