### ISSUE TITLE
What is slide 40 (Moving tables from C/AL to Extension) telling me?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#19]
I have the feeling I need to read a lot between the lines in slide 40. Having read and mostly understood the topic https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-overview-v15 on slide 39 (Upgrade documentation) seems not to help me out.

Moving tables from C/AL to Extension seems to imply that I have already converted my C/AL table definition to an AL table definition that resides in an extension. Should I understand it this way that when bringing my 14.x database to 15.x, having my code converted, the platform will than move my old c/al sql table to a new extension sql table. From:
![afbeelding](https://user-images.githubusercontent.com/18466198/72104356-89feaa00-332b-11ea-95b1-5f6cf4a35805.png)
to
![afbeelding](https://user-images.githubusercontent.com/18466198/72104362-8d923100-332b-11ea-93fe-3ce453b2c661.png)
Is that right?

**Comment by nikolakukrika** [comment]
Correct. The move happens automatically. You need to convert the code first.
