### ISSUE TITLE
Update extension

### ISSUE THREAD

**Issue by developmentleasba** [microsoft/BCUpgrade#2]
Good morning from Spain.
We are Leasba Consulting S.L., Microsoft partner. We want to update an extensión to a higher version but the following error appears: "The application object of type 'Table' with the ID '50102' is defined in multiple apps. The apps are: ExtensionName by Leasba Consulting, SL 1.0.4.4; ExtensionName by Leasba Consulting, SL 1.0.4.5."
How could we fix it? We can't unistall the extension because it has a Table with data.
Best, Alejandro

**Comment by freddydk** [comment]
You need to uninstall and unpublish - and then publish and run data upgrade for the app.
described here:
https://freddysblog.com/2019/12/09/having-demo-data-while-developing-business-central-apps-with-docker/
and here:
https://freddysblog.com/2019/11/24/upgrading-to-15-x-from-14-x-c-al-our-nav-techdays-2019-demo/

**Comment by nikolakukrika** [comment]
The uninstall and unpublish will not delete the data. The data will be preserved. There is a special switch that deletes the extension's data.
