### ISSUE TITLE
Slide 41 (Moving tables from C/AL into Extension): what Guid?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#21]
Slide 41 states:

> In SQL Guid is appended

What Guid is this? Is this the $systemId as discussed on previous slides (regarding integration management)?

**Comment by nikolakukrika** [comment]
Updated to this:

The move is simple – app will take the ownership of the tables automatically. 
For this to happen we need to append the App Id guid to all tables that app owns in SQL and update the metadata in related system tables (Nav Object Metadata and similar).

Move will be executed only if Name and ID of the Table matches in C/AL and AL. Fields are not used to determine if table can be moved to extension automatically . If the fields do not match, we will move the table and Latter upgrade steps will most likely fail.
