### ISSUE TITLE
Slide 42 (Moving tables to AL): what is the animation actually showing?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#24]
The animation on slide 42 is showing three steps:
1. tables before move
![afbeelding](https://user-images.githubusercontent.com/18466198/72107472-b3bacf80-3331-11ea-9525-ebd184910fcf.png)

1. first moved tables
![afbeelding](https://user-images.githubusercontent.com/18466198/72107463-ae5d8500-3331-11ea-9525-43d6ce8454d2.png)

1. second moved tables
![afbeelding](https://user-images.githubusercontent.com/18466198/72107449-a7367700-3331-11ea-94e2-85c66bb81737.png)

How do the powershell statement lines relate to the three steps? To what does step 2 relate? To what does step 3 relate?

**Comment by nikolakukrika** [comment]
Updated the slide. The steps outlined are not correct, this is for demonstration purposes what happens when you sync the slide. Look at the powershell for true reference.
