### ISSUE TITLE
DestinationAppsForMigration not mentioned

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#26]
The NAV TechDays presentation _Using Docker and the ContainerHelper to convert your C/AL solution to an AL_ had a couple of slides on DestinationAppsForMigration. They seem to be **not** in _the big upgrade deck_.
![image](https://user-images.githubusercontent.com/18466198/72257960-2ca97800-360d-11ea-8a45-f7fc85a2164d.png)

**Comment by nikolakukrika** [comment]
It is - Slide 91. I have added FAQ on the slide 92
