### ISSUE TITLE
Typo 1: slide 50 (step 3 explained)

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#3]
![afbeelding](https://user-images.githubusercontent.com/18466198/72063302-d0c3b400-32d9-11ea-8a61-224cb3fd74ae.png)
Change _could_ to **cloud**.

**Note**
I am preparing my next weeks DDC presentation (and the week after a webinar on the same) " Upgrade to BC, how do you do that?" https://register.gotowebinar.com/register/8611050017033409548

It's an investigation for the upgrade w are planning. As such I am happily making use of http://aka.ms/bcupgradedeck. Now studying the .pptx running into a number various typos, but also statements that could use some elaboration. Hre is the first typo. Will report more and, more important to me, will also pose relevant questions on unclear parts.

**Comment by nikolakukrika** [comment]
Fixed thanks
