### ISSUE TITLE
Task 14: Upgrade on table migration extension error

### ISSUE THREAD

**Issue by davmac1** [microsoft/BCUpgrade#31]
I received an error on https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app
task 14 - previous version does not exist. (This is the table migration.)
I ignored it since I had already synced it (sync-navapp) and the data was migrated.
Task 15 upgrades to the other extensions worked without errors.

Does table migration extension need the upgrade:
Start-NAVAppDataUpgrade -ServerInstance BC160 -Name "TableMigration" -version 1.0.0.1
previous version is 1.0.0.0
Or can I ignore it?

**Comment by davmac1** [comment]
I found I have another problem - the routine did not have a problem with table extensions and the fields getting prefixes in the upgrade because the field numbers stayed the same.
It did not handle the tables though - it did not look at table numbers - it looked at table names, so my ISV (GCX ) and custom (PTE ) did not work - it could not find the tables - is there a way to have it handle table extension migration by having it use the table numbers instead?

**Comment by nikolakukrika** [comment]
For task 14 - previous version does not exist. (This is the table migration.), it should have been published under Task 9: Publish symbols and DestinationAppsForMigrations

It needs to be upgraded, otherwise the schema will not be completed. 

You cannot add prefixes, the system unfortunately requires both ID and Name to match. Rename of the tables is possible in C/AL I believe, C/AL works on the IDs. If these do not match, the C/AL tables will be left behind (not get the guid).

**Comment by davmac1** [comment]
The tables moved, but not the data - it did drop the original tables - I did do a force which is maybe why it dropped the add-on tables.
I will see if I can handle the renames in C/AL then.

**Comment by nikolakukrika** [comment]
If you have force synced the tables, that would drop all the data. Only solution is to either rename оr upgrade with COPY while on 14, or to obsolete and loop over all fields in AL.

**Comment by nikolakukrika** [comment]
@davmac1 - If you have more questions I would recommend to continue here: https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035. There is more people that can help both from MS and Partner channel, plus I'm getting updates sooner. Let me know if you have problems joining.
