### ISSUE TITLE
error Sync-NAVApp upgrade from BC14 to BC20

### ISSUE THREAD

**Issue by monicasuica** [microsoft/BCUpgrade#33]
Hi,

I'm facing an error at task 11 when upgrading from BC14 to BC20 Onprem (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v20) :
![image](https://user-images.githubusercontent.com/47560247/175349139-dbb6ee5a-c652-4184-a3e8-9968ba63c876.png)
![image](https://user-images.githubusercontent.com/47560247/175349360-cf46e653-5a0b-4d76-b74e-18a17b9c58b0.png)

In the event viewer a more detailed error is shown:
erver instance: BC200 Tenant ID: default Environment Name: Environment Type: Production Session type: Background Session ID: 6 User: 
  CustCORP\criteria Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavSqlException ErrorNumber: 15248 TransactionRolledBack: False MaxVerbosity: Off ErrorCode: -1 
  SuppressMessage: False ContainsPersonalOrRestrictedInformation: True DiagnosticsSuppress: False 
  DiagnosticsMessage: Message not shown because the NavBaseException constructor was used without privacy classification
  MessageWithoutPrivateInformation: Message not shown because the NavBaseException constructor was used without privacy classification 
  SuppressExceptionCreatedEvent: False FatalityScope: None ErrorLevel: Error Message: The following SQL error was unexpected: 
  Either the parameter @objname is ambiguous or the claimed @objtype (INDEX) is wrong. Caution: Changing any part of an object name could break scripts and stored procedures. 
  Caution: Changing any part of an object name could break scripts and stored procedures. Caution: 
  Changing any part of an object name could break scripts and stored procedures. Caution: 
  Changing any part of an object name could break scripts and stored procedures. Caution: 
  Changing any part of an object name could break scripts and stored procedures. Caution: 
  Changing any part of an object name could break scripts and stored procedures. 
  SQL statement: exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$1"', N'$Key2', N'INDEX'; 
  exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$2"', N'$Key3', N'INDEX'; 
  exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$3"', N'$Key4', N'INDEX'; 
  exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$4"', N'$Key5', N'INDEX';
  exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$7"', N'$Key8', N'INDEX'; 
  exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$8"', N'$Key9', N'INDEX'; 
  exec sp_rename N'"dbo"."CompName$G_L Account$68b58c83-f442-4d2f-b6a1-ed26a3f1328c"."$9"', N'$Key10', N'INDEX' 
  StackTrace: at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo) at System.Environment.get_StackTrace() at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.Throw

Does anyone have any hints why this is happenning?

Thank you!

**Comment by nikolakukrika** [comment]
This is an old GIThub with examples how to migrate via powershell. The issue that you are having is rather specific.

Please join us at:
https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=48311992320&view=all
or at https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035

If you are having issues joining yammer let me know. I will forward the request to relevant people.
