### ISSUE TITLE
Base Application upgrade from BC16 to BC23 with CRM Integrtion fails

### ISSUE THREAD

**Issue by dipl-ing** [microsoft/BCUpgrade#34]
Hi!

I'm making an onPrem test upgrade from BC16 to BC23, everything was going smooth, until I started the Base Application upgrade. 
In the live environment, the CRM Integration is working fine, and on the upgraded environment nothing was changed on it.

I tried the New-NAVTableConnection, but not sure which parameters are required, or how exactly the connection string should look like.

And finally, the error message I get:

Start-NAVAppDataUpgrade : Could not upgrade the extension 'Base Application' by 'Microsoft' from version '16.3.14085.14238' to '23.0.12034.12841' for tenant 'default' and company 'company_name_was_here' due to the following error: 'Table connection  for table type CRM must be registered using RegisterTableConnection or cmdlet New-NAVTableConnection before it can be used.' and AL stack trace:
"CRM Integration Management"(CodeUnit 5330).AddExtraFieldMappings line 35 - Base Application by Microsoft
"CDS Setup Defaults"(CodeUnit 7204).AddExtraIntegrationFieldMappings line 9 - Base Application by Microsoft
"Upgrade - BaseApp"(CodeUnit 104000).UpgradeAddExtraIntegrationFieldMappings line 22 - Base Application by Microsoft
"Upgrade - BaseApp"(CodeUnit 104000).OnUpgradePerCompany line 23 - Base Application by Microsoft
"Upgrade Triggers"(CodeUnit 2000000008).OnUpgradePerCompany(Event) line 2

Any ideas how to make it work, or how should we proceed for the test upgrade, and then at the live one?

Best Regards,
Attila

**Comment by nikolakukrika** [comment]
This github is not maintained any more, it is old. Please go to
aka.ms/bccloudmigrationyammer and ask the question there
