### ISSUE TITLE
Structure of slide deck makes not much sense

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#7]
![afbeelding](https://user-images.githubusercontent.com/18466198/72081250-6e30df00-32fe-11ea-9787-53510fb42ef5.png)
The intro is valid, but the rest is nonsense. WOuld be very helpful if the rest of slides would get assigned to proper sections.
This could be a possible structure:
![afbeelding](https://user-images.githubusercontent.com/18466198/72082467-7db12780-3300-11ea-97ad-3e69ef84a948.png)

**Comment by nikolakukrika** [comment]
Thanks for the feedback. I will hav eto see how to restructure based on the comment. I currently do not have time to do this :). I will leave this issue open, if anyone else has any comments please share them.

**Comment by lvanvugt** [comment]
Will I upload my version?

**Comment by nikolakukrika** [comment]
Hi Luc,

You can send it to me by mail, I can put it on the git. It is easier than adding you as a contributor :) - This is a Microsoft owned GitHub, so I'm not sure how the rules apply regarding external contributors.

**Comment by lvanvugt** [comment]
Hey, Nikola. Did send you the deck some time ago. Not succeeded to upload it or give me right to push it at least?
