### ISSUE TITLE
Slide 16 could use some more details

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#9]
![afbeelding](https://user-images.githubusercontent.com/18466198/72095219-5bc39f00-3318-11ea-8600-730fa2653d69.png)
Two things
1. I do see two columns, but the do not have headers: left column describing the change and right colums describing refactor action; please add these two a headers to the columns; this make it much more helpful
1. These examples are taken from a case that has not been discussed on previous slides; I know I have seen it somewhere (docs.microsoft?) but cannot find it; please add reference (or somewhat more extensive description on slides) to help me as a reader to better understand

**Comment by nikolakukrika** [comment]
It used to be specific, it is not anymore.
I have updated the slide to sort out the confusion.
